apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PWD
              value: "123"
            - name: RABBIT_HOST
              value: "rabbitmq-cluster"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_PWD
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer